build-release:
    cargo build --release

build-debug:
    cargo build

clippy:
    cd src/userspace && cargo clippy -- -D warnings
    cargo clippy -- -D warnings

clean:
    rm -f src/kernel/compiled_userspace/*
    rm -f src/kernel/src/autogenerated/userspace_programs.rs
    rm -rf target-userspace
    cargo clean

debugCommand := "cargo run -- -s -S"
debugReleaseCommand := "cargo run --release -- -s -S"

run:
    cargo run --release

run-debug:
    cargo run

test:
    cargo test --release

miri: build-debug
    cargo miri test --target riscv64gc-unknown-linux-gnu

run-vscode:
    cargo run -- -s -S && echo "DONE"

test-vscode:
    cargo test -- -s -S && echo "DONE"

debug:
    tmux new-session -d '{{debugCommand}}' \; split-window -h 'gdb-multiarch $(pwd)/target/riscv64gc-unknown-none-elf/debug/kernel -ex "target remote :1234"' \; attach

debugf FUNC:
    tmux new-session -d '{{debugCommand}}' \; split-window -h 'gdb-multiarch $(pwd)/target/riscv64gc-unknown-none-elf/debug/kernel -ex "target remote :1234" -ex "hbreak {{FUNC}}"' \; attach

debug-release:
    tmux new-session -d '{{debugReleaseCommand}}' \; split-window -h 'gdb-multiarch $(pwd)/target/riscv64gc-unknown-none-elf/release/kernel -ex "target remote :1234"' \; attach

debug-releasef FUNC:
    tmux new-session -d '{{debugReleaseCommand}}' \; split-window -h 'gdb-multiarch $(pwd)/target/riscv64gc-unknown-none-elf/release/kernel -ex "target remote :1234" -ex "hbreak {{FUNC}}"' \; attach

disassm-release: build-release
    riscv64-unknown-elf-objdump -d target/riscv64gc-unknown-none-elf/release/kernel | less

addr2line ADDR:
    riscv64-unknown-elf-addr2line -e target/riscv64gc-unknown-none-elf/release/kernel {{ADDR}}