build:
    cargo build --release

clippy:
    cd userspace && cargo clippy -- -D warnings
    cargo clippy -- -D warnings

clean:
    rm -f kernel/compiled_userspace/*
    rm -f kernel/src/autogenerated/userspace_programs.rs
    rm -rf target-userspace
    cargo clean

debugReleaseCommand := "cargo run --release -- -s -S"

run:
    cargo run --release

run-debug:
    cargo run

test:
    cargo test --release

miri: build
    MIRIFLAGS="-Zmiri-permissive-provenance -Zmiri-env-forward=RUST_BACKTRACE" RUST_BACKTRACE=1 cargo miri test --target riscv64gc-unknown-linux-gnu

debug:
    tmux new-session -d '{{debugReleaseCommand}}' \; split-window -h 'gdb-multiarch $(pwd)/target/riscv64gc-unknown-none-elf/release/kernel -ex "target remote :1234"' \; attach

debugf FUNC:
    tmux new-session -d '{{debugReleaseCommand}}' \; split-window -h 'gdb-multiarch $(pwd)/target/riscv64gc-unknown-none-elf/release/kernel -ex "target remote :1234" -ex "hbreak {{FUNC}}" -ex "c"'\; attach

disassm: build
    riscv64-unknown-elf-objdump -d --demangle --disassembler-color=on visualize-jumps=extended-color target/riscv64gc-unknown-none-elf/release/kernel | less

addr2line ADDR:
    riscv64-unknown-elf-addr2line -f -p -i -C -e target/riscv64gc-unknown-none-elf/release/kernel {{ADDR}}
