#![cfg_attr(not(miri), no_std)]
#![cfg_attr(not(miri), no_main)]
#![cfg_attr(miri, allow(dead_code))]
#![feature(panic_info_message)]
#![feature(strict_provenance)]
#![feature(nonzero_ops)]
#![feature(custom_test_frameworks)]
#![feature(const_mut_refs)]
#![feature(option_take_if)]
#![feature(non_null_convenience)]
#![feature(pointer_is_aligned)]
#![feature(exposed_provenance)]
#![feature(lazy_cell)]
#![feature(let_chains)]
#![feature(stmt_expr_attributes)]
#![test_runner(test::test_runner)]
#![reexport_test_harness_main = "test_main"]

use crate::{
    interrupts::plic,
    io::uart::QEMU_UART,
    memory::page_tables,
    pci::{enumerate_devices, get_pci_host_bridge_address},
    processes::{scheduler, timer},
};

mod asm;
mod assert;
mod autogenerated;
mod cpu;
mod device_tree;
mod interrupts;
mod io;
mod klibc;
mod logging;
mod memory;
mod panic;
mod pci;
mod processes;
mod sbi;
mod syscalls;

mod test;

#[macro_use]
extern crate alloc;

extern "C" {
    static HEAP_START: usize;
    static HEAP_SIZE: usize;
}

#[no_mangle]
extern "C" fn kernel_init(hart_id: usize, mut device_tree_pointer: *const ()) {
    QEMU_UART.lock().init();

    println!("Hello World from YaROS!\n");
    println!("Hart ID: {}", hart_id);
    println!("Device Tree Pointer: {:p}", device_tree_pointer);

    let version = sbi::extensions::base_extension::sbi_get_spec_version();
    info!("SBI version {}.{}", version.major, version.minor);
    assert!(
        (version.major == 0 && version.minor >= 2) || version.major > 0,
        "Supported SBI Versions >= 0.2"
    );

    // The device tree must be parsed before the page allocator is initialized
    // Otherwise we could accidentally overwrite the device tree
    let dtb = device_tree::parse(device_tree_pointer);
    println!("Device Tree:\n{:?}", dtb);
    assert!(
        dtb.get_reserved_areas().is_empty(),
        "There should be no reserved memory regions"
    );

    for node in dtb.get_structure_block() {
        debug!("{:?}", node);
    }

    let structured_block = dtb.get_structure_block();
    let pci_host_bridge_address = get_pci_host_bridge_address(structured_block)
        .expect("PCI Host Bridge Address must be known.");

    // Forget device tree because it could be overwritten by the page allocator
    let _ = dtb;
    #[allow(unused_assignments)]
    device_tree_pointer = core::ptr::null();

    unsafe {
        info!("Initializing page allocator");
        info!(
            "Heap Start: {:#x}-{:#x} (size: {:#x})",
            HEAP_START,
            HEAP_START + HEAP_SIZE,
            HEAP_SIZE
        );
        memory::init_page_allocator(HEAP_START, HEAP_SIZE);
    }

    // This function uses allocations. Therefore put this after initialization of the page allocator
    enumerate_devices(pci_host_bridge_address);

    #[cfg(test)]
    test_main();

    page_tables::activate_page_table(&page_tables::KERNEL_PAGE_TABLES.lock());

    interrupts::set_sscratch_to_kernel_trap_frame();

    plic::init_uart_interrupt();

    scheduler::initialize();
    timer::set_timer(0);
}
